DELETE FROM sims_class where 1=1;
DELETE FROM sims_student where 1=1;
DELETE FROM sims_teacher where 1=1;

INSERT INTO sims_class
(COLLEGE_ID, CLASS_ID, CLASS_NAME)
VALUES('1', '11', '高一一班');

INSERT INTO sims_class
(COLLEGE_ID, CLASS_ID, CLASS_NAME)
VALUES('1', '12', '高一二班');

INSERT INTO sims_teacher
(COLLEGE_ID, TEACHER_ID, TEACHER_NAME)
VALUES('1', '111', '张三');

INSERT INTO sims_student
(COLLEGE_ID, CLASS_ID, STUDENT_ID, STUDENT_NAME)
VALUES('collage', '1', '1', '张三');

INSERT INTO sims_student
(COLLEGE_ID, CLASS_ID, STUDENT_ID, STUDENT_NAME, ENG_NAME, ID_CARD_NO, MOBILE_PHONE, GENDER, MONTHLY_SALARY, BIRTH, AVATAR, HEIGHT, WEIGHT, NATION, POLITICAL, MARITAL, DOMICILE_PLACE_PROVINCE, DOMICILE_PLACE_CITY, DOMICILE_PLACE_ADDRESS, HOBBY, INTRO, PRESENT_ADDRESS, EMAIL, ENTRY_DATE, STATUS, TENANT_ID, REVISION, CREATED_BY, CREATED_TIME, UPDATED_BY, UPDATED_TIME)
VALUES('collage', '1', '2', '李四', NULL, NULL, NULL, 'M', NULL, NULL, NULL, NULL, NULL, '01', NULL, 'UNMARRIED', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Normal', NULL, NULL, NULL, NULL, NULL, NULL);


