DELETE FROM sims_college where 1=1;
DELETE FROM sims_teacher where 1=1;
DELETE FROM sims_student where 1=1;

INSERT INTO SIMS_CLASS(CLASS_ID, CLASS_NAME) VALUES('9527', '鲁班');

INSERT INTO sims_college (COLLEGE_ID, COLLEGE_NAME) VALUES('1', '金鹰学院');
INSERT INTO sims_college (COLLEGE_ID, COLLEGE_NAME) VALUES('2', '频繁学院');

INSERT INTO sims_teacher (COLLEGE_ID, TEACHER_ID, TEACHER_NAME) VALUES('1', '111', '金应');
INSERT INTO sims_teacher (COLLEGE_ID, TEACHER_ID, TEACHER_NAME) VALUES('2', '211', '平樊');

INSERT INTO sims_student (COLLEGE_ID, CLASS_ID, STUDENT_ID, STUDENT_NAME)
VALUES('1', '11', '1111', '张三');
INSERT INTO sims_student (COLLEGE_ID, CLASS_ID, STUDENT_ID, STUDENT_NAME)
VALUES('1', '11', '1112', '李四');
INSERT INTO sims_student (COLLEGE_ID, CLASS_ID, STUDENT_ID, STUDENT_NAME)
VALUES('2', '21', '2111', '王五');
