DROP TABLE IF EXISTS SIMS_COLLEGE;
CREATE TABLE SIMS_COLLEGE(
    COLLEGE_ID VARCHAR(32) NOT NULL   COMMENT '学院ID' ,
    COLLEGE_NAME VARCHAR(90)    COMMENT '学院名称' ,
    SHORT_NAME VARCHAR(90)    COMMENT '学院简称' ,
    INTRO VARCHAR(900)    COMMENT '学院介绍' ,
    PROFESSION_NUMBER INT    COMMENT '专业个数' ,
    STUDENT_NUMBER INT    COMMENT '学生人数' ,
    PRESIDENT VARCHAR(90)    COMMENT '院长' ,
    TENANT_ID VARCHAR(32)    COMMENT '租户号' ,
    REVISION INT    COMMENT '乐观锁' ,
    CREATED_BY VARCHAR(32)    COMMENT '创建人' ,
    CREATED_TIME DATETIME    COMMENT '创建时间' ,
    UPDATED_BY VARCHAR(32)    COMMENT '更新人' ,
    UPDATED_TIME DATETIME    COMMENT '更新时间' ,
    PRIMARY KEY (COLLEGE_ID)
)  COMMENT = '学院';

DROP TABLE IF EXISTS SIMS_MAJOR;
CREATE TABLE SIMS_MAJOR(
    MAJOR_ID VARCHAR(32) NOT NULL   COMMENT '专业ID' ,
    MAJOR_NAME VARCHAR(90)    COMMENT '专业名称' ,
    SHORT_NAME VARCHAR(90)    COMMENT '专业简称' ,
    ESTAB_DATE DATETIME    COMMENT '开设日期' ,
    INTRO VARCHAR(900)    COMMENT '专业介绍' ,
    TUITION_FEE DECIMAL(24,6)    COMMENT '学费' ,
    TENANT_ID VARCHAR(32)    COMMENT '租户号' ,
    REVISION INT    COMMENT '乐观锁' ,
    CREATED_BY VARCHAR(32)    COMMENT '创建人' ,
    CREATED_TIME DATETIME    COMMENT '创建时间' ,
    UPDATED_BY VARCHAR(32)    COMMENT '更新人' ,
    UPDATED_TIME DATETIME    COMMENT '更新时间' ,
    PRIMARY KEY (MAJOR_ID)
)  COMMENT = '专业';

DROP TABLE IF EXISTS SIMS_CLASS;
CREATE TABLE SIMS_CLASS(
    COLLEGE_ID VARCHAR(32)    COMMENT '所在学院' ,
    MAJOR_ID VARCHAR(32)    COMMENT '所属专业ID' ,
    CLASS_ID VARCHAR(32) NOT NULL   COMMENT '班级ID' ,
    CLASS_NAME VARCHAR(90)    COMMENT '班级名称' ,
    STUDENT_NUMBER INT    COMMENT '班级人数' ,
    ADVISER VARCHAR(90)    COMMENT '辅导员' ,
    ESTAB_DATE DATETIME    COMMENT '成立时间' ,
    YEAR_NUMBER INT    COMMENT '学习年数' ,
    TENANT_ID VARCHAR(32)    COMMENT '租户号' ,
    REVISION INT    COMMENT '乐观锁' ,
    CREATED_BY VARCHAR(32)    COMMENT '创建人' ,
    CREATED_TIME DATETIME    COMMENT '创建时间' ,
    UPDATED_BY VARCHAR(32)    COMMENT '更新人' ,
    UPDATED_TIME DATETIME    COMMENT '更新时间' ,
    PRIMARY KEY (CLASS_ID)
)  COMMENT = '班级';

DROP TABLE IF EXISTS SIMS_STUDENT;
CREATE TABLE SIMS_STUDENT(
    COLLEGE_ID VARCHAR(32) NOT NULL   COMMENT '所在学院ID' ,
    CLASS_ID VARCHAR(32) NOT NULL   COMMENT '所在班级ID' ,
    STUDENT_ID VARCHAR(32) NOT NULL   COMMENT '学生ID' ,
    STUDENT_NAME VARCHAR(90)    COMMENT '学生姓名' ,
    ENG_NAME VARCHAR(90)    COMMENT '英文名' ,
    ID_CARD_NO VARCHAR(255)    COMMENT '身份证号' ,
    MOBILE_PHONE VARCHAR(255)    COMMENT '手机号' ,
    GENDER VARCHAR(32)   DEFAULT 'M' COMMENT '性别' ,
    MONTHLY_SALARY DECIMAL(24,6)    COMMENT '月薪' ,
    BIRTH DATETIME    COMMENT '出生日期' ,
    AVATAR INT    COMMENT '头像' ,
    HEIGHT INT    COMMENT '身高' ,
    WEIGHT INT    COMMENT '体重' ,
    NATION VARCHAR(32)   DEFAULT '01' COMMENT '名族' ,
    POLITICAL VARCHAR(32)    COMMENT '政治面貌' ,
    MARITAL VARCHAR(32)   DEFAULT 'UNMARRIED' COMMENT '婚姻状况' ,
    DOMICILE_PLACE_PROVINCE VARCHAR(255)    COMMENT '籍贯（省）' ,
    DOMICILE_PLACE_CITY VARCHAR(255)    COMMENT '籍贯（市）' ,
    DOMICILE_PLACE_ADDRESS VARCHAR(255)    COMMENT '户籍地址' ,
    HOBBY VARCHAR(255)    COMMENT '爱好' ,
    INTRO VARCHAR(900)    COMMENT '简要介绍' ,
    PRESENT_ADDRESS VARCHAR(255)    COMMENT '居住地址' ,
    EMAIL VARCHAR(255)    COMMENT '电子邮件' ,
    ENTRY_DATE DATETIME    COMMENT '入学日期' ,
    STATUS VARCHAR(32)   DEFAULT 'Normal' COMMENT '状态' ,
    TENANT_ID VARCHAR(32)    COMMENT '租户号' ,
    REVISION INT    COMMENT '乐观锁' ,
    CREATED_BY VARCHAR(32)    COMMENT '创建人' ,
    CREATED_TIME DATETIME    COMMENT '创建时间' ,
    UPDATED_BY VARCHAR(32)    COMMENT '更新人' ,
    UPDATED_TIME DATETIME    COMMENT '更新时间' ,
    PRIMARY KEY (STUDENT_ID)
)  COMMENT = '学生';


CREATE INDEX idx_smis_student_01 ON SIMS_STUDENT(STUDENT_NAME,ENG_NAME);
CREATE INDEX idx_smis_student_cert ON SIMS_STUDENT(ID_CARD_NO);

DROP TABLE IF EXISTS SIMS_TEACHER;
CREATE TABLE SIMS_TEACHER(
    COLLEGE_ID VARCHAR(32) NOT NULL   COMMENT '所在学院ID' ,
    TEACHER_ID VARCHAR(32) NOT NULL   COMMENT '教师ID' ,
    TEACHER_NAME VARCHAR(90)    COMMENT '姓名' ,
    GENDER VARCHAR(32)   DEFAULT 'M' COMMENT '性别' ,
    BIRTH DATETIME    COMMENT '出生日期' ,
    GRADUATE_INSTITUTION VARCHAR(90)    COMMENT '毕业院校' ,
    PRACTICE_YEARS INT    COMMENT '从业年限' ,
    POLITICAL VARCHAR(32)    COMMENT '政治面貌' ,
    MARITAL VARCHAR(32)   DEFAULT 'UNMARRIED' COMMENT '婚姻状况' ,
    AVATAR VARCHAR(255)    COMMENT '头像' ,
    INTRO VARCHAR(900)    COMMENT '介绍' ,
    TENANT_ID VARCHAR(32)    COMMENT '租户号' ,
    REVISION INT    COMMENT '乐观锁' ,
    CREATED_BY VARCHAR(32)    COMMENT '创建人' ,
    CREATED_TIME DATETIME    COMMENT '创建时间' ,
    UPDATED_BY VARCHAR(32)    COMMENT '更新人' ,
    UPDATED_TIME DATETIME    COMMENT '更新时间' ,
    PRIMARY KEY (TEACHER_ID)
)  COMMENT = '教师';

DROP TABLE IF EXISTS SIMS_LESSON;
CREATE TABLE SIMS_LESSON(
    LESSON_ID VARCHAR(32) NOT NULL   COMMENT '课程ID' ,
    LESSON_NAME VARCHAR(90)    COMMENT '课程名' ,
    INTRO VARCHAR(900)    COMMENT '课程说明' ,
    HOURS INT    COMMENT '学时' ,
    SCORE INT    COMMENT '学分' ,
    TENANT_ID VARCHAR(32)    COMMENT '租户号' ,
    REVISION INT    COMMENT '乐观锁' ,
    CREATED_BY VARCHAR(32)    COMMENT '创建人' ,
    CREATED_TIME DATETIME    COMMENT '创建时间' ,
    UPDATED_BY VARCHAR(32)    COMMENT '更新人' ,
    UPDATED_TIME DATETIME    COMMENT '更新时间' ,
    PRIMARY KEY (LESSON_ID)
)  COMMENT = '课程';

DROP TABLE IF EXISTS SIMS_INSTRUCT;
CREATE TABLE SIMS_INSTRUCT(
    INSTRUCT_ID VARCHAR(32) NOT NULL   COMMENT '授课号' ,
    CLASS_ID VARCHAR(32)    COMMENT '班级ID' ,
    LESSON_ID VARCHAR(32)    COMMENT '课程号' ,
    TEACHER_ID VARCHAR(32)    COMMENT '教师ID' ,
    TENANT_ID VARCHAR(32)    COMMENT '租户号' ,
    REVISION INT    COMMENT '乐观锁' ,
    CREATED_BY VARCHAR(32)    COMMENT '创建人' ,
    CREATED_TIME DATETIME    COMMENT '创建时间' ,
    UPDATED_BY VARCHAR(32)    COMMENT '更新人' ,
    UPDATED_TIME DATETIME    COMMENT '更新时间' ,
    PRIMARY KEY (INSTRUCT_ID)
)  COMMENT = '授课';

DROP TABLE IF EXISTS SIMS_EXAM;
CREATE TABLE SIMS_EXAM(
    EXAM_ID VARCHAR(32) NOT NULL   COMMENT '考试记录ID' ,
    STUDENT_ID VARCHAR(32)    COMMENT '学生ID' ,
    LESSON_ID VARCHAR(32)    COMMENT '课程ID' ,
    EXAM_DATE DATETIME    COMMENT '考试日期' ,
    EXAM_NAME VARCHAR(90)    COMMENT '考试名' ,
    EXAM_SCORE DECIMAL(24,6)    COMMENT '考试分数' ,
    TENANT_ID VARCHAR(32)    COMMENT '租户号' ,
    REVISION INT    COMMENT '乐观锁' ,
    CREATED_BY VARCHAR(32)    COMMENT '创建人' ,
    CREATED_TIME DATETIME    COMMENT '创建时间' ,
    UPDATED_BY VARCHAR(32)    COMMENT '更新人' ,
    UPDATED_TIME DATETIME    COMMENT '更新时间' ,
    PRIMARY KEY (EXAM_ID)
)  COMMENT = '考试';

DROP TABLE IF EXISTS SIMS_CLASS_FEE;
CREATE TABLE SIMS_CLASS_FEE(
    TENANT_ID VARCHAR(32)    COMMENT '租户号' ,
    REVISION VARCHAR(32)    COMMENT '乐观锁' ,
    CREATED_BY VARCHAR(32)    COMMENT '创建人' ,
    CREATED_TIME DATETIME    COMMENT '创建时间' ,
    UPDATED_BY VARCHAR(32)    COMMENT '更新人' ,
    UPDATED_TIME DATETIME    COMMENT '更新时间'
)  COMMENT = '班费';

CREATE VIEW SMIS_STUDENT_EXAM AS
SELECT
    SIMS_STUDENT.STUDENT_ID AS STUDENT_ID,
    SIMS_STUDENT.STUDENT_NAME AS STUDENT_NAME,
    SIMS_STUDENT.MOBILE_PHONE AS MOBILE_PHONE,
    SIMS_STUDENT.GENDER AS GENDER,
    SIMS_LESSON.LESSON_NAME AS LESSON_NAME,
    SIMS_LESSON.LESSON_ID AS LESSON_ID,
    SIMS_EXAM.EXAM_DATE AS EXAM_DATE,
    SIMS_EXAM.EXAM_SCORE AS EXAM_SCORE,
    SIMS_EXAM.TENANT_ID AS TENANT_ID,
    SIMS_EXAM.REVISION AS REVISION,
    SIMS_EXAM.CREATED_BY AS CREATED_BY,
    SIMS_EXAM.CREATED_TIME AS CREATED_TIME,
    SIMS_EXAM.UPDATED_BY AS UPDATED_BY,
    SIMS_EXAM.UPDATED_TIME AS UPDATED_TIME
FROM SIMS_STUDENT,SIMS_LESSON,SIMS_EXAM;

CREATE VIEW V_CLASS_STUDENT AS
SELECT
    SIMS_CLASS.CLASS_NAME AS CLASS_NAME,
    SIMS_STUDENT.ENG_NAME AS ENG_NAME,
    SIMS_STUDENT.STUDENT_NAME AS STUDENT_NAME,
    SIMS_STUDENT.STUDENT_ID AS STUDENT_ID,
    SIMS_STUDENT.CLASS_ID AS CLASS_ID,
    SIMS_STUDENT.COLLEGE_ID AS COLLEGE_ID,
    SIMS_CLASS.ADVISER AS ADVISER,
    SIMS_STUDENT.ID_CARD_NO AS ID_CARD_NO,
    SIMS_STUDENT.MOBILE_PHONE AS MOBILE_PHONE,
    SIMS_STUDENT.GENDER AS GENDER,
    SIMS_STUDENT.MARITAL AS MARITAL,
    SIMS_STUDENT.POLITICAL AS POLITICAL,
    SIMS_STUDENT.BIRTH AS BIRTH
FROM SIMS_CLASS,SIMS_STUDENT;

