DELETE FROM sims_class where 1=1;
DELETE FROM sims_student where 1=1;

INSERT INTO sims_class
(COLLEGE_ID, MAJOR_ID, CLASS_ID, CLASS_NAME, STUDENT_NUMBER, ADVISER, ESTAB_DATE, YEAR_NUMBER, TENANT_ID, REVISION, CREATED_BY, CREATED_TIME, UPDATED_BY, UPDATED_TIME)
VALUES('collage', 'major', '1', '高一三班', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO sims_student
(COLLEGE_ID, CLASS_ID, STUDENT_ID, STUDENT_NAME, ENG_NAME, ID_CARD_NO, MOBILE_PHONE, GENDER, MONTHLY_SALARY, BIRTH, AVATAR, HEIGHT, WEIGHT, NATION, POLITICAL, MARITAL, DOMICILE_PLACE_PROVINCE, DOMICILE_PLACE_CITY, DOMICILE_PLACE_ADDRESS, HOBBY, INTRO, PRESENT_ADDRESS, EMAIL, ENTRY_DATE, STATUS, TENANT_ID, REVISION, CREATED_BY, CREATED_TIME, UPDATED_BY, UPDATED_TIME)
VALUES('collage', '1', '1', '张三', NULL, NULL, NULL, 'M', NULL, NULL, NULL, NULL, NULL, '01', NULL, 'UNMARRIED', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Normal', NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO sims_student
(COLLEGE_ID, CLASS_ID, STUDENT_ID, STUDENT_NAME, ENG_NAME, ID_CARD_NO, MOBILE_PHONE, GENDER, MONTHLY_SALARY, BIRTH, AVATAR, HEIGHT, WEIGHT, NATION, POLITICAL, MARITAL, DOMICILE_PLACE_PROVINCE, DOMICILE_PLACE_CITY, DOMICILE_PLACE_ADDRESS, HOBBY, INTRO, PRESENT_ADDRESS, EMAIL, ENTRY_DATE, STATUS, TENANT_ID, REVISION, CREATED_BY, CREATED_TIME, UPDATED_BY, UPDATED_TIME)
VALUES('collage', '1', '2', '李四', NULL, NULL, NULL, 'M', NULL, NULL, NULL, NULL, NULL, '01', NULL, 'UNMARRIED', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Normal', NULL, NULL, NULL, NULL, NULL, NULL);
