{
  "properties" : { },
  "id" : "d062db46897c4a1fb93ca187ebe44a2f",
  "script" : null,
  "groupId" : "9219a9a8cdb9442d820f0770ccf483ab",
  "name" : "函数嵌套",
  "createTime" : 1679877668325,
  "updateTime" : 1615985594130,
  "lock" : null,
  "createBy" : null,
  "updateBy" : null,
  "path" : "nested",
  "description" : null,
  "returnType" : null,
  "mappingPath" : null,
  "parameters" : [ ]
}
================================
import '@/test/add' as add;
return add(1,2);